Update Git repository using egup-single

diff --git a/support/autodep b/support/autodep
--- a/support/autodep
+++ b/support/autodep
@@ -125,4 +125,13 @@ fi
 
 # Install internetarchive
 
-sudo -H "$pip_command" install internetarchive
+    if ! pip_loc="$(type -p "pip3")" || [[ -z $pip_loc ]]; then
+        pip_needed="true"
+    else
+        pip_command="pip3"
+        pip_needed="false"
+    fi
+if ! sudo -H "$pip_command" install internetarchive; then
+    echo "ERROR: Could not find or install internetarchive."
+    exit 1
+fi
