Update Git repository using egup-single

diff --git a/support/autodep b/support/autodep
--- a/support/autodep
+++ b/support/autodep
@@ -1,67 +1,28 @@
 #!/usr/bin/env bash
+# shellcheck disable=SC1091
+source ember_bash_setup &> /dev/null
+
+trap 'die "A fatal error was reported on ${BASH_SOURCE[0]} line ${LINENO} in $(pwd)."' ERR
 #set -x
 
-# Should work without ember-shared or crystallize, just in case, so don't set traps or source ember_bash_setup
+if [[ "$OSTYPE" = darwin* ]]; then
+    scripts/emberMacGNUUpgrade
+    find scripts -type f -exec perl -0777 -p -i -e 's/readlink /greadlink /g' {} \;
+    find scripts -type f -exec perl -0777 -p -i -e 's/dirname /gdirname /g' {} \;
+    find scripts -type f -exec perl -0777 -p -i -e 's/sort /gsort /g' {} \;
+    find scripts -type f -exec perl -0777 -p -i -e 's/stdbuf /gstdbuf /g' {} \;
+    find scripts -type f -exec perl -0777 -p -i -e 's/sha256sum /gsha256sum /g' {} \;
+    find scripts -type f -exec perl -0777 -p -i -e 's/sha512sum /gsha512sum /g' {} \;
+    find scripts -type f -exec perl -0777 -p -i -e 's/ncdu /8731d097a5ed41149c7ffb67756c310e /g' {} \;
+    find scripts -type f -exec perl -0777 -p -i -e 's/du /gdu /g' {} \;
+    find scripts -type f -exec perl -0777 -p -i -e 's/8731d097a5ed41149c7ffb67756c310e /ncdu /g' {} \;
+    find scripts -type f -exec perl -0777 -p -i -e 's/sed /gsed /g' {} \;
+    find scripts -type f -exec perl -0777 -p -i -e 's/find /gfind /g' {} \;
+    find scripts -type f -exec perl -0777 -p -i -e 's/stat /gstat /g' {} \;
+fi
+rm scripts/emberMacGNUUpgrade
 
-#NOTE: MAINTENANCE: Manual error printing
-trap 'printf '\''%b'\'' '\''\033[1;31m'\'' >&2; echo "A fatal error was reported on ${BASH_SOURCE[0]} line ${LINENO} in $(pwd)." >&2; printf '\''%b'\'' '\''\033[0m'\'' >&2; exit 1' ERR
-
-# NOTE: MAINTENANCE: Inlined function from ember_bash_setup
-emdate() (
-    # If changing this, also change the copy in the error-notify script and possibly also the copy in the emberMacGNUUpgrade script.
-    trap 'die "A fatal error was reported on ${BASH_SOURCE[0]} line ${LINENO} in $(pwd)."' ERR
-
-    local temp
-    temp="$(date +%Y-%m-%d-%H-%M-%S-%N)_$(xxd -pu <<< "$(date +%z)")"
-    echo "${temp//-/}"
-)
-
-# NOTE: MAINTENANCE: Inlined function from ember_bash_setup
-date-uuid() (
-    trap 'die "A fatal error was reported on ${BASH_SOURCE[0]} line ${LINENO} in $(pwd) at $(emdate)."' ERR
-
-    local temp
-    temp="$(emdate)-$(python -c 'import uuid; print str(uuid.uuid4())')"
-    echo "${temp//-/}"
-)
-
-# NOTE: MAINTENANCE: Inlined function from ember_bash_setup
-setVariableToCommandOutput() {
-    if [[ "$1" == "emSetVariableToCommandOutputVar" ]]; then
-        return 1
-    fi
-    emSetVariableToCommandOutputVar="$1"
-    shift
-    save_traps="$(trap)"
-    trap - ERR
-    IFS= read -rd '' "$emSetVariableToCommandOutputVar" < <( "$@" )
-    trap 'die "A fatal error was reported on ${BASH_SOURCE[0]} line ${LINENO} in $(pwd) at $(emdate)."' ERR
-    eval "$save_traps"
-}
-
-# NOTE: MAINTENANCE: Inlined function from ember_bash_setup
-eescape() {
-    (
-        export eescapeString="$1"
-        local temp
-        # shellcheck disable=SC2016
-        setVariableToCommandOutput temp bash -c 'perl -0777 -e '\''print(quotemeta($ENV{eescapeString}))'\'' | sed '\''s/\\$//'\'' | sed '\''s/\\\r/\r/'\'
-        temp="${temp//$'\n'/'\n'}"
-        printf "%s" "${temp//$'\r'/'\r'}"
-    )
-}
-
-# NOTE: MAINTENANCE: Inlined function from ember_bash_setup
-ereplace() {
-    (
-        # Perl returns 0 even if it can't find the file (without extra perl code), so test first.
-        if [[ ! -e "$3" ]]; then
-            die "The target file does not exist."
-        fi
-        setVariableToCommandOutput ereplaceFrom eescape "$1"
-        export ereplaceFrom
-        ereplaceTo="$2"
-        export ereplaceTo
-        perl -0777 -p -i -e 's/$ENV{ereplaceFrom}/$ENV{ereplaceTo}/g' "$3"
-    )
-}
+if [[ "$OSTYPE" = darwin* ]]; then
+    sudo ./support/macRootPrepare
+    sudo chsh -s /usr/local/bin/bash "$USER"
+fi
