Update Git repository using egup-single

diff --git a/support/install-core b/support/install-core
--- a/support/install-core
+++ b/support/install-core
@@ -2,7 +2,7 @@
 
 # Should work without ember-shared
 
-trap 'echo "Error preparing module"; exit 1' ERR
+trap 'echo "Error installing module"; exit 1' ERR
 
 if [[ -e "support/.modules-prepared" ]]; then
     # Has already been run
