Update Ember tree

diff --git a/support/install b/support/install
--- a/support/install
+++ b/support/install
@@ -5,6 +5,50 @@
 
 trap 'printf '\''%b'\'' '\''\033[1;31m'\'' >&2; echo "A fatal error was reported on ${BASH_SOURCE[0]} line ${LINENO} in $(pwd)." >&2; printf '\''%b'\'' '\''\033[0m'\'' >&2; exit 1' ERR
 
+setVariableToCommandOutput() {
+    if [[ "$1" == "emSetVariableToCommandOutputVar" ]]; then
+        return 1
+    fi
+    emSetVariableToCommandOutputVar="$1"
+    shift
+    save_traps="$(trap)"
+    trap - ERR
+    IFS= read -rd '' "$emSetVariableToCommandOutputVar" < <( "$@" )
+    trap 'die "A fatal error was reported on ${BASH_SOURCE[0]} line ${LINENO} in $(pwd) at $(emdate)."' ERR
+    eval "$save_traps"
+}
+
+eescape() {
+    (
+        export eescapeString="$1"
+        local temp
+        # shellcheck disable=SC2016
+        setVariableToCommandOutput temp bash -c 'perl -0777 -e '\''print(quotemeta($ENV{eescapeString}))'\'' | sed '\''s/\\$//'\'' | sed '\''s/\\\r/\r/'\'
+        temp="${temp//$'\n'/'\n'}"
+        printf "%s" "${temp//$'\r'/'\r'}"
+    )
+}
+
+ereplace() {
+    (
+        # Perl returns 0 even if it can't find the file (without extra perl code), so test first.
+        if [[ ! -e "$3" ]]; then
+            die "The target file does not exist."
+        fi
+        setVariableToCommandOutput ereplaceFrom eescape "$1"
+        export ereplaceFrom
+        ereplaceTo="$2"
+        export ereplaceTo
+        perl -0777 -p -i -e 's/$ENV{ereplaceFrom}/$ENV{ereplaceTo}/g' "$3"
+    )
+}
+
+skipConfigFile="false"
+if [[ "$1" == "--skip-config-file" ]]; then
+    skipConfigFile="true"
+    shift
+fi
+
 echo 1 "$1" 2 "$2" 3 "$3" 4 "$4" 5 "$5" 6 "$6" 7 "$7" 8 "$8" 9 "$9"
 if [[ -n "$1" ]]; then
     emberSharedDestdir="$1"
