Update Git repository using egup-single

diff --git a/support/prepare b/support/prepare
--- a/support/prepare
+++ b/support/prepare
@@ -83,7 +83,7 @@ else
         packageName="$(<package-name)"
         if ! ebs_loc="$(type -P "ember_bash_setup_core")" || [[ -z "$ebs_loc" ]]; then
             printf '%b' '\033[1;31m' >&2
-            echo "ERROR: ember-shared core module is not properly installed! It must be installed before installing $packageName." >&2
+            echo "ERROR: ember-shared core module is not properly installed! It must be installed before installing $packageName module $module." >&2
             printf '%b' '\033[0m' >&2
             exit 1
         fi
