Update Ember tree

diff --git a/ember_bash_setup b/ember_bash_setup
--- a/ember_bash_setup
+++ b/ember_bash_setup
@@ -1,6 +1,9 @@
 #!/usr/bin/env bash
 
-export emberSharedVersion='1.1.2'
+export emberSharedVersion='1.1.3'
+
+# Allow problems to be caught within pipelines
+set +o pipefail
 
 # More verbose debugging
 PS4='+($?) $BASH_SOURCE:$FUNCNAME:$LINENO:'
@@ -127,3 +130,5 @@ function ia() {
         fi
     )
 }
+
+trap 'error-notify "An error was reported on ${BASH_SOURCE[0]} line ${LINENO}."' ERR
