Update Ember tree

diff --git a/ember_bash_setup b/ember_bash_setup
--- a/ember_bash_setup
+++ b/ember_bash_setup
@@ -119,22 +119,26 @@ preadconf() {
 }
 
 ia() {
-    (
-        # Retry wrapper for ia to work around https://github.com/jjjake/internetarchive/issues/183
-        # Should strip delete option from ia arguments and implement it outside of the retry loop to prevent a hypothetical case (I think I might have just seen this) where ia deletes when it fails
-        retryCount=0
-        succeeded="false"
-        while [[ "$succeeded" != "true" && retryCount -lt 30 ]]; do
-            "$(which ia)" "$@" && succeeded="true"
-            retryCount=$(( retryCount + 1 ))
-            if [[ "$retryCount" -gt 1 ]]; then
-                sleep 60
+    if [[ "$1" == "upload" ]]; then
+        (
+            # Retry wrapper for ia to work around https://github.com/jjjake/internetarchive/issues/183
+            # Should strip delete option from ia arguments and implement it outside of the retry loop to prevent a hypothetical case (I think I might have just seen this) where ia deletes when it fails
+            retryCount=0
+            succeeded="false"
+            while [[ "$succeeded" != "true" && retryCount -lt 30 ]]; do
+                "$(which ia)" "$@" && succeeded="true"
+                retryCount=$(( retryCount + 1 ))
+                if [[ "$retryCount" -gt 1 ]]; then
+                    sleep 60
+                fi
+            done
+            if [[ "$retryCount" -ge 30 ]]; then
+                exit 1
             fi
-        done
-        if [[ "$retryCount" -ge 30 ]]; then
-            exit 1
-        fi
-    )
+        )
+    else
+        "$(which ia)" "$@"
+    fi
 }
 
 urlencode() {
