Update Git repository using egup-single

diff --git a/data/doc/app-buildsystem-template/configure b/data/doc/app-buildsystem-template/configure
--- a/data/doc/app-buildsystem-template/configure
+++ b/data/doc/app-buildsystem-template/configure
@@ -26,15 +26,13 @@ if ! ebs_loc="$(type -P "ember_bash_setup_core")" || [[ -z "$ebs_loc" ]]; then
     fi
 fi
 
-eiteDie() {
-    #NOTE: MAINTENANCE: Manual error printing
-    if ! ebs_loc="$(type -P "ember_bash_setup_core")" || [[ -z "$ebs_loc" ]]; then
-        printf '%b' '\033[1;31m' >&2
-        echo "ERROR: ember-shared core module is not properly installed! It must be installed before installing $packageName." >&2
-        printf '%b' '\033[0m' >&2
-        exit 1
-    fi
-}
+#NOTE: MAINTENANCE: Manual error printing
+if ! ebs_loc="$(type -P "ember_bash_setup_core")" || [[ -z "$ebs_loc" ]]; then
+    printf '%b' '\033[1;31m' >&2
+    echo "ERROR: ember-shared core module is not properly installed! It must be installed before installing $packageName." >&2
+    printf '%b' '\033[0m' >&2
+    exit 1
+fi
 
 if ! ebs_loc="$(type -P "ember_bash_setup")" || [[ -z "$ebs_loc" ]]; then
     eiteDie || exit 1
