Update Git repository using egup-single

diff --git a/data/doc/app-buildsystem-template/configure b/data/doc/app-buildsystem-template/configure
--- a/data/doc/app-buildsystem-template/configure
+++ b/data/doc/app-buildsystem-template/configure
@@ -47,4 +47,8 @@ if [[ -z "$sharedDataDir" ]]; then
     exit 1
 fi
 buildsystemDir="$(getEmberSharedDataDir)/app-buildsystem"
+if ! [[ -d "$buildsystemDir" ]]; then
+    echo "Could not get ember-shared build directory. Perhaps the installed version is too old?"
+    exit 1
+fi
 source "$buildsystemDir/configure"
