Update Ember tree

diff --git a/scripts/csum b/scripts/csum
--- a/scripts/csum
+++ b/scripts/csum
@@ -5,7 +5,7 @@ source ember_bash_setup &> /dev/null
 
 ((EUID)) && exec sudo -- "$0" "$@"
 
-trap 'error-notify "A fatal error was reported on ${BASH_SOURCE[0]} line ${LINENO}."; exit 1' ERR
+trap 'error-notify "A fatal error was reported on ${BASH_SOURCE[0]} line ${LINENO} at $(emdate)."; exit 1' ERR
 
 action="--save"
 if [[ "$1" == "--save" ]]; then
@@ -55,7 +55,7 @@ case $action in
             rm "/tmp/${streamId:?}"
         fi
     }
-    trap 'error-notify "A fatal error was reported on ${BASH_SOURCE[0]} line ${LINENO}."; finish; exit 1' ERR
+    trap 'error-notify "A fatal error was reported on ${BASH_SOURCE[0]} line ${LINENO} at $(emdate)."; finish; exit 1' ERR
     trap finish EXIT
 
     if [[ -z "$checksumFile" ]]; then
diff --git a/scripts/ember_bash_setup b/scripts/ember_bash_setup
--- a/scripts/ember_bash_setup
+++ b/scripts/ember_bash_setup
@@ -2,10 +2,10 @@
 
 # set -x
 
-export emberSharedVersion='1.1.4.81'
+export emberSharedVersion='1.1.4.82'
 
 # The update script shown here requires there to be only one ebuild of ember-bash-setup in the wreathe-overlay overlay.
-# ( sudo true; newVersion="1.1.4.81"; cd "/Ember Library/Ember satellite projects/ember-shared"; eogup-single; git tag -a "v$newVersion" -m "version"; egup-single .; cd "/Ember Library/Ember satellite projects/wreathe-overlay"; eogup-single; mv app-misc/ember-shared/ember-shared-*.ebuild "app-misc/ember-shared/ember-shared-$newVersion.ebuild"; repoman manifest; egup-single; sudo layman -s wreathe-overlay; sudo emerge ember-shared )
+# ( sudo true; newVersion="1.1.4.82"; cd "/Ember Library/Ember satellite projects/ember-shared"; eogup-single; git tag -a "v$newVersion" -m "version"; egup-single .; cd "/Ember Library/Ember satellite projects/wreathe-overlay"; eogup-single; mv app-misc/ember-shared/ember-shared-*.ebuild "app-misc/ember-shared/ember-shared-$newVersion.ebuild"; repoman manifest; egup-single; sudo layman -s wreathe-overlay; sudo emerge ember-shared )
 
 if [[ "$1" == "--version" ]]; then
     esVersionA="$(sed '6q;d' "$(which ember_bash_setup)")"
@@ -84,7 +84,7 @@ setVariableToCommandOutput() {
     save_traps="$(trap)"
     trap - ERR
     IFS= read -rd '' "$emSetVariableToCommandOutputVar" < <( "$@" )
-    trap 'die "A fatal error was reported on ${BASH_SOURCE[0]} line ${LINENO}."' ERR
+    trap 'die "A fatal error was reported on ${BASH_SOURCE[0]} line ${LINENO} at $(emdate)."' ERR
     eval "$save_traps"
 }
 
@@ -99,8 +99,14 @@ emdate() (
     echo "${temp//-/}"
 )
 
+emlogsignature() (
+    trap 'die "A fatal error was reported on ${BASH_SOURCE[0]} line ${LINENO} at $(emdate)."' ERR
+
+    echo "$(emdate):${BASH_SOURCE[0]} line ${LINENO}"
+)
+
 date-uuid() (
-    trap 'die "A fatal error was reported on ${BASH_SOURCE[0]} line ${LINENO}."' ERR
+    trap 'die "A fatal error was reported on ${BASH_SOURCE[0]} line ${LINENO} at $(emdate)."' ERR
 
     temp="$(emdate)-$(python -c 'import uuid; print str(uuid.uuid4())')"
     echo "${temp//-/}"
@@ -360,7 +366,7 @@ checkedxz() (
     assert() {
         local save_traps
         save_traps="$(trap)"
-        trap 'die "Assertion failed: $(join_by ", " "$@") "'"on ${BASH_SOURCE[0]} line ${LINENO}." ERR
+        trap 'die "Assertion failed: $(join_by ", " "$@") "'"on ${BASH_SOURCE[0]} line ${LINENO} at $(emdate)." ERR
         local verbose=""
         if [[ "$1" == "-v" ]]; then
             verbose="true"
@@ -513,4 +519,4 @@ checkedxz() (
     }
 }
 
-trap 'error-notify "An error was reported on ${BASH_SOURCE[0]} line ${LINENO}."' ERR
+trap 'error-notify "An error was reported on ${BASH_SOURCE[0]} line ${LINENO} at $(emdate)."' ERR
