Update Git repository using egup-single

diff --git a/scripts/ember_bash_setup b/scripts/ember_bash_setup
--- a/scripts/ember_bash_setup
+++ b/scripts/ember_bash_setup
@@ -637,6 +637,26 @@ ia() (
                 cat "$path"
             fi
         fi
+    elif [[ "$1" == "metaXMLStored" ]]; then
+        backupLocation="$(crystallize-getconf BackupLocation)"
+        mkdir -p "$backupLocation/metadataStored/filesXMLs"
+        ident="$(iaident "$2")"
+        if [[ "false" != "$propagateMetadataRetrieval" ]]; then
+            # Download and save the other metadata to ensure it's all available for the item
+            ia --no-propagate-metadata-retrieval metadataStored "$ident" > /dev/null
+            ia --no-propagate-metadata-retrieval listStored "$ident" > /dev/null
+        fi
+        path="$backupLocation/metadataStored/filesXMLs/$ident"_files.xml
+        if [[ -e "$path" ]] && [[ "$(wc -c < "$path")" -gt 1 ]]; then
+            cat "$path"
+        else
+            retryUntilSuccess 30 30 5 5 wget -qO - "https://archive.org/download/$ident/$ident"_files.xml > "$path"
+            if [[ 0 != "$?" ]]; then
+                die "Could not get files XML for $ident."
+            else
+                cat "$path"
+            fi
+        fi
     elif [[ "$1" == "metadataStored" ]]; then
         backupLocation="$(crystallize-getconf BackupLocation)"
         mkdir -p "$backupLocation/metadataStored/metadata"
