Update Git repository using egup-single

diff --git a/scripts/ember_bash_setup b/scripts/ember_bash_setup
--- a/scripts/ember_bash_setup
+++ b/scripts/ember_bash_setup
@@ -791,10 +791,16 @@ firefox-places-dump() {
     if [[ -n "$1" ]]; then
         firefoxProfile="$1"
     else
-        firefoxProfile="$(cd; get-default-firefox-profile)"
+        # shellcheck disable=SC2119
+        firefoxProfile="$(cd ~ || die "Could not cd to home folder"; get-default-firefox-profile)"
     fi
     sqlite3 "$firefoxProfile/places.sqlite" '.sch' > firefox-places-dump.schema.sql
     sqlite3 "$firefoxProfile/places.sqlite" '.dump' > firefox-places-dump.sql
+    cp "$firefoxProfile/sessionstore.js" firefox-places-dump.sessionstore.js
+    # Put newline every other character, to make it easier on git storage
+    sed 's/\(.\)/\1\n/g' -i firefox-places-dump.schema.sql
+    sed 's/\(.\)/\1\n/g' -i firefox-places-dump.sql
+    sed 's/\(.\)/\1\n/g' -i firefox-places-dump.sessionstore.js
 }
 
 bigSponge() (
