Update Git repository using egup-single

diff --git a/scripts/ember_bash_setup b/scripts/ember_bash_setup
--- a/scripts/ember_bash_setup
+++ b/scripts/ember_bash_setup
@@ -634,6 +634,9 @@ ia() (
         else
             temp="$(tempFile)"
             retryUntilSuccess 30 30 5 5 wget -qO - "https://archive.org/download/$ident/$ident"_files.xml > "$temp"
+            if [[ 0 != "$?" ]]; then
+                die "Could not get files XML for $ident."
+            fi
             tempSha="$(sha512sum "$temp" | awk '{print $1;}')"
             retryUntilSuccess 30 30 5 5 wget -qO - "https://archive.org/download/$ident/$ident"_files.xml > "$temp"
             if [[ 0 != "$?" ]]; then
