Update Git repository using egup-single

diff --git a/scripts/ember_bash_setup b/scripts/ember_bash_setup
--- a/scripts/ember_bash_setup
+++ b/scripts/ember_bash_setup
@@ -543,9 +543,20 @@ ia() (
         # Test items: UntilR2V232017june27447p has commas; futuramerlin.archival.data.24nov2013 is messy
         ia listStored "$2" | sed -E 's/^([^"]*,[^"]*)$/"\1"/g' | csvfix printf -fmt '%s'
     elif [[ "$1" == "listStored" ]]; then
-        # Wrapper around ia list.
-        # Test items: UntilR2V232017june27447p has commas; futuramerlin.archival.data.24nov2013 is messy
-        ia list "$2" | sed -E 's/^([^"]*,[^"]*)$/"\1"/g' | csvfix printf -fmt '%s'
+        backupLocation="$(crystallize-getconf BackupLocation)"
+        mkdir -p "$backupLocation/metadataStored"
+        ident="$(iaident "$2")"
+        path="$backupLocation/metadataStored/$ident.json"
+        if [[ -e "$path" ]] && [[ "$(wc -c < "$path")" -gt 1 ]]; then
+            cat "$path"
+        else
+            retryUntilSuccess 30 30 5 5 command ia metadata "$ident" > "$path"
+            if [[ 0 != "$?" ]]; then
+                die "Could not get metadata for $ident."
+            else
+                cat "$path"
+            fi
+        fi
     elif [[ "$1" == "metadataStored" ]]; then
         backupLocation="$(crystallize-getconf BackupLocation)"
         mkdir -p "$backupLocation/metadataStored"
