Update Ember tree

diff --git a/scripts/ember_bash_setup b/scripts/ember_bash_setup
--- a/scripts/ember_bash_setup
+++ b/scripts/ember_bash_setup
@@ -446,7 +446,14 @@ iafilename() (
 
 iasha1() (
     local field="sha1"
-    result="$(ia metadata "$(iaident "$1")" | { jq -r '.files[] | select(.name=="'"$(iafilename "$1")"'").'"$field" 2>/dev/null; };)"
+    local result
+    if [[ "$(iapath "$1")" == "$(iaident "$1")"_files.xml ]]; then
+        metadataPath="$(tempFile)"
+        wget -O "$metadataPath" "https://archive.org/download/$(iaident "$1")"_files.xml || die "Could not retrieve item files xml!"
+        result="$(sha1sum "$metadataPath" | awk '{print $1;}')"
+    else
+        result="$(ia metadata "$(iaident "$1")" | { jq -r '.files[] | select(.name=="'"$(iafilename "$1")"'").'"$field" 2>/dev/null; };)"
+    fi
     # jq seems to exit 0 on at least some errors
     [[ -z "$result" ]] && exit 1
     print "$result"
