Update Git repository using egup-single

diff --git a/scripts/ember_bash_setup b/scripts/ember_bash_setup
--- a/scripts/ember_bash_setup
+++ b/scripts/ember_bash_setup
@@ -773,8 +773,11 @@ git-bulk-sync() {
 
 get-default-firefox-profile() (
     # based on https://askubuntu.com/questions/239543/get-the-default-firefox-profile-directory-from-bash
-    [[ -n "$1" ]]; then
-    cd ~/.mozilla/firefox || die "Could not cd to ~/.mozilla/firefox"
+    if [[ -n "$1" ]]; then
+        cd "$1" || die "Could not cd to the specified directory"
+    else
+        cd ~/.mozilla/firefox || die "Could not cd to ~/.mozilla/firefox"
+    fi
     if grep -q '\[Profile[^0]\]' profiles.ini; then
         grep -E '^\[Profile|^Path|^Default' profiles.ini | grep -1 '^Default=1' | grep '^Path' | cut -c6-
     else
@@ -785,7 +788,11 @@ get-default-firefox-profile() (
 firefox-places-dump() {
     # help from https://gist.github.com/kirang89/6541591
     local firefoxProfile
-    firefoxProfile="$(cd; get-default-firefox-profile)"
+    if [[ -n "$1" ]]; then
+        firefoxProfile="$1"
+    else
+        firefoxProfile="$(cd; get-default-firefox-profile)"
+    fi
     sqlite3 "$firefoxProfile/places.sqlite" '.sch' > firefox-places-dump.schema.sql
     sqlite3 "$firefoxProfile/places.sqlite" '.dump' > firefox-places-dump.sql
 }
