Update Ember tree

diff --git a/scripts/ember_bash_setup b/scripts/ember_bash_setup
--- a/scripts/ember_bash_setup
+++ b/scripts/ember_bash_setup
@@ -2,10 +2,10 @@
 
 #set -x
 
-export emberSharedVersion='1.1.4.242'
+export emberSharedVersion='1.1.4.243'
 
 # The update script shown here requires there to be only one ebuild of ember-shared in the wreathe-overlay overlay.
-# ( sudo true; newVersion="1.1.4.242"; cd "/Ember Library/Ember satellite projects/ember-shared"; eogup-single; git tag -a "v$newVersion" -m "version"; egup-single .; cd "/Ember Library/Ember satellite projects/wreathe-overlay"; eogup-single; mv app-misc/ember-shared/ember-shared-*.ebuild "app-misc/ember-shared/ember-shared-$newVersion.ebuild"; repoman manifest; egup-single; sudo layman -s wreathe-overlay; sudo emerge ember-shared; sudo dispatch-conf )
+# ( sudo true; newVersion="1.1.4.243"; cd "/Ember Library/Ember satellite projects/ember-shared"; eogup-single; git tag -a "v$newVersion" -m "version"; egup-single .; cd "/Ember Library/Ember satellite projects/wreathe-overlay"; eogup-single; mv app-misc/ember-shared/ember-shared-*.ebuild "app-misc/ember-shared/ember-shared-$newVersion.ebuild"; repoman manifest; egup-single; sudo layman -s wreathe-overlay; sudo emerge ember-shared; sudo dispatch-conf )
 
 # To use the --version option of ember_bash_setup, it is necessary to have e8787d06e61943a6874e94985b53bc0a="2dee41bf-53fb-4f65-997f-33bf50bfbb4d" and run ember_bash_setup --version. It may be important to run unset e8787d06e61943a6874e94985b53bc0a afterwards.
 d1875509777f46809ff940e0aad970f0=""
@@ -448,7 +448,7 @@ iasha1() (
     local field="sha1"
     local result
     if [[ "$(iapath "$1")" == "$(iaident "$1")"_files.xml ]]; then
-        # TODO: Decide whether this is the right way to go about this. Right now, because item files xmls don't have checksums available for them from IA (since they're where the checksums are kept), this is retrieving it and calculating the checksums dynamically. This could be suboptimal since there is no guarantee that the returned value is correct.
+        # TODO: Decide whether this is the right way to go about this. Right now, because item files xmls don't have checksums available for them from IA (since they're where the checksums are kept), this is retrieving it and calculating the checksums dynamically. This could be suboptimal (or even harmful) since there is no guarantee that the returned value is correct.
         metadataPath="$(tempFile)"
         fcache_request "https://archive.org/download/$(iaident "$1")"_files.xml | "$metadataPath" || die "Could not retrieve item files xml!"
         result="$(sha1sum "$metadataPath" | awk '{print $1;}')"
@@ -462,7 +462,15 @@ iasha1() (
 
 iamd5() (
     local field="md5"
-    result="$(ia metadata "$(iaident "$1")" | { jq -r '.files[] | select(.name=="'"$(iafilename "$1")"'").'"$field" 2>/dev/null; };)"
+    local result
+    if [[ "$(iapath "$1")" == "$(iaident "$1")"_files.xml ]]; then
+        # TODO: Decide whether this is the right way to go about this. Right now, because item files xmls don't have checksums available for them from IA (since they're where the checksums are kept), this is retrieving it and calculating the checksums dynamically. This could be suboptimal (or even harmful) since there is no guarantee that the returned value is correct.
+        metadataPath="$(tempFile)"
+        fcache_request "https://archive.org/download/$(iaident "$1")"_files.xml | "$metadataPath" || die "Could not retrieve item files xml!"
+        result="$(md5sum "$metadataPath" | awk '{print $1;}')"
+    else
+        result="$(ia metadata "$(iaident "$1")" | { jq -r '.files[] | select(.name=="'"$(iafilename "$1")"'").'"$field" 2>/dev/null; };)"
+    fi
     # jq seems to exit 0 on at least some errors
     [[ -z "$result" ]] && exit 1
     print "$result"
