Update Ember tree

diff --git a/scripts/ember_bash_setup b/scripts/ember_bash_setup
--- a/scripts/ember_bash_setup
+++ b/scripts/ember_bash_setup
@@ -2,10 +2,10 @@
 
 # set -x
 
-export emberSharedVersion='1.1.4.114'
+export emberSharedVersion='1.1.4.115'
 
 # The update script shown here requires there to be only one ebuild of ember-shared in the wreathe-overlay overlay.
-# ( sudo true; newVersion="1.1.4.114"; cd "/Ember Library/Ember satellite projects/ember-shared"; eogup-single; git tag -a "v$newVersion" -m "version"; egup-single .; cd "/Ember Library/Ember satellite projects/wreathe-overlay"; eogup-single; mv app-misc/ember-shared/ember-shared-*.ebuild "app-misc/ember-shared/ember-shared-$newVersion.ebuild"; repoman manifest; egup-single; sudo layman -s wreathe-overlay; sudo emerge ember-shared )
+# ( sudo true; newVersion="1.1.4.115"; cd "/Ember Library/Ember satellite projects/ember-shared"; eogup-single; git tag -a "v$newVersion" -m "version"; egup-single .; cd "/Ember Library/Ember satellite projects/wreathe-overlay"; eogup-single; mv app-misc/ember-shared/ember-shared-*.ebuild "app-misc/ember-shared/ember-shared-$newVersion.ebuild"; repoman manifest; egup-single; sudo layman -s wreathe-overlay; sudo emerge ember-shared )
 
 # To use the --version option of ember_bash_setup, it is necessary to have e8787d06e61943a6874e94985b53bc0a="2dee41bf-53fb-4f65-997f-33bf50bfbb4d" and run ember_bash_setup --version. It may be important to run unset e8787d06e61943a6874e94985b53bc0a afterwards.
 d1875509777f46809ff940e0aad970f0=""
@@ -425,8 +425,7 @@ checkedxz() (
     assert() {
         local save_traps
         save_traps="$(trap)"
-        #trap 'die "Assertion failed: $(join_by ", " "$@") '"on ${BASH_SOURCE[0]} line ${LINENO} in $(pwd) at $(emdate)."'"' ERR
-        trap 'echo "Bomecieh"' ERR
+        trap 'die "Assertion failed: $(join_by ", " "$@") '"on ${BASH_SOURCE[0]} line ${LINENO} in $(pwd) at $(emdate)."'"' ERR
         local verbose=""
         if [[ "$1" == "-v" ]]; then
             verbose="true"
@@ -437,6 +436,8 @@ checkedxz() (
 
         case $assertionTest in
         directoryEquals)
+            # trap is workaround for https://lists.gnu.org/archive/html/bug-bash/2016-02/msg00140.html
+            trap 'die "Assertion failed: $(join_by ", " "$@") '"on ${BASH_SOURCE[0]} line ${LINENO} in $(pwd) at $(emdate)."'"' ERR
             firstDir="$1"
             secondDir="$2"
             if [[ -z "$firstDir" ]] || [[ -z "$secondDir" ]]; then
@@ -449,21 +450,23 @@ checkedxz() (
             fi
             ;;
         fileEquals)
+            # trap is workaround for https://lists.gnu.org/archive/html/bug-bash/2016-02/msg00140.html
+            trap 'die "Assertion failed: $(join_by ", " "$@") '"on ${BASH_SOURCE[0]} line ${LINENO} in $(pwd) at $(emdate)."'"' ERR
             firstFile="$1"
             secondFile="$2"
             if [[ -z "$firstFile" ]] || [[ -z "$secondFile" ]]; then
                 die "Both values must be non-empty."
             fi
-            assert equals "$(sha512sum "$firstFile" | awk '{print $1;}')" "$(sha512sum "$secondFile" | awk '{print $1;}')"
-            trap
-            false
-            echo $?
-            die
+            # || die is workaround for https://lists.gnu.org/archive/html/bug-bash/2016-02/msg00140.html
+            assert equals "$(sha512sum "$firstFile" | awk '{print $1;}')" "$(sha512sum "$secondFile" | awk '{print $1;}')" || die "Assertion failed: $(join_by ", " "$@") on  line 1 in /home/kyan at 20171101123757491216040_2d303430300a."
             ;;
         equals)
+            # trap is workaround for https://lists.gnu.org/archive/html/bug-bash/2016-02/msg00140.html
+            trap 'die "Assertion failed: $(join_by ", " "$@") '"on ${BASH_SOURCE[0]} line ${LINENO} in $(pwd) at $(emdate)."'"' ERR
             [[ "${1:?}" == "${2:?}" ]]
             ;;
         *)
+            trap 'error-notify "An error was reported on ${BASH_SOURCE[0]} line ${LINENO} in $(pwd) at $(emdate)."' ERR
             die "Unknown test."
             ;;
         esac
