Update Git repository using egup-single

diff --git a/scripts/ember_bash_setup b/scripts/ember_bash_setup
--- a/scripts/ember_bash_setup
+++ b/scripts/ember_bash_setup
@@ -384,7 +384,7 @@ ia() (
                         else
                             fileToQuery="$remoteNameOverride"
                         fi
-                        retryUntilSuccess 300 60 5 5 iasha1 "$identifier/$fileToQuery" > /dev/null || die "Could not get checksum for uploaded file $identifier/$fileToQuery."
+                        retryUntilSuccess 5000 60 5 5 iasha1 "$identifier/$fileToQuery" > /dev/null || die "Could not get checksum for uploaded file $identifier/$fileToQuery."
                         checksumLine="$(iasha1 "$identifier/$fileToQuery")"
                         if [[ "$checksumLine" != "$knownChecksum" ]]; then
                             die "ERROR! Checksum known by Internet Archive $checksumLine does not match saved checksum known locally $knownChecksum."
@@ -538,6 +538,10 @@ ia() (
             fileName="${fileName##*\/}"
             ia downloadAsStream "$requestUrl" > "$fileName" || die
         ) || die
+    elif [[ "$1" == "listplain" ]]; then
+        # Wrapper around ia list.
+        # Test items: UntilR2V232017june27447p has commas; futuramerlin.archival.data.24nov2013 is messy
+        ia list "$2" | sed -E 's/^([^"]*,[^"]*)$/"\1"/g' | csvfix printf -fmt '%s'
     elif [[ "$1" == "listplain" ]]; then
         # Wrapper around ia list.
         # Test items: UntilR2V232017june27447p has commas; futuramerlin.archival.data.24nov2013 is messy
