Update Git repository using egup-single

diff --git a/scripts/ember_bash_setup b/scripts/ember_bash_setup
--- a/scripts/ember_bash_setup
+++ b/scripts/ember_bash_setup
@@ -636,6 +636,9 @@ ia() (
             retryUntilSuccess 30 30 5 5 wget -qO - "https://archive.org/download/$ident/$ident"_files.xml > "$temp"
             tempSha="$(sha512sum "$temp" | awk '{print $1;}')"
             retryUntilSuccess 30 30 5 5 wget -qO - "https://archive.org/download/$ident/$ident"_files.xml > "$temp"
+            if [[ 0 != "$?" ]]; then
+                die "Could not get files XML for $ident."
+            fi
             [[ "$(sha512sum "$temp" | awk '{print $1;}')" == "$tempSha" ]] || die "files XML was different when downloaded twice"
             mv "$temp" "$path"
             if [[ 0 != "$?" ]]; then
