Update Ember tree

diff --git a/scripts/ember_bash_setup b/scripts/ember_bash_setup
--- a/scripts/ember_bash_setup
+++ b/scripts/ember_bash_setup
@@ -241,27 +241,91 @@ findso() {
     /sbin/ldconfig -p | awk -v needle="$1" '$1 == needle {sub(/.* => /, ""); print}'
 }
 
-assert() {
-    verbose=""
-    if [[ "$1" == "-v" ]]; then
-        verbose="true"
-        shift
-    fi
-    assertionTest="$1"
-    shift
-
-    case $assertionTest in
-    directoryEquals)
-        if [[ "$verbose" == "true" ]]; then
-            diff -uraN "$1" "$2"
-        else
-            diff -uraN "$1" "$2" > /dev/null
+testFramework() {
+    assert() {
+        verbose=""
+        if [[ "$1" == "-v" ]]; then
+            verbose="true"
+            shift
         fi
-        ;;
-    *)
-        die "Unknown test."
-        ;;
-    esac
+        assertionTest="$1"
+        shift
+
+        case $assertionTest in
+        directoryEquals)
+            if [[ "$verbose" == "true" ]]; then
+                diff -uraN "$1" "$2"
+            else
+                diff -uraN "$1" "$2" > /dev/null
+            fi
+            ;;
+        *)
+            die "Unknown test."
+            ;;
+        esac
+    }
+
+    succeededTests="0"
+    failedTests="0"
+    totalTests="0"
+
+    verboseTests=""
+
+    runTest() {
+        local verbose="$verboseTests"
+        if [[ "$1" == "-v" ]]; then
+            verbose="true"
+            shift
+        fi
+        totalTests=$(( totalTests + 1 ))
+        local testName="$1"
+        testSucceed() {
+            echo "Test $testName succeeded."
+            succeededTests=$(( succeededTests + 1 ))
+        }
+        testFail() {
+            echo "Test $testName failed."
+            failedTests=$(( failedTests + 1 ))
+        }
+        if [[ -d "$testName" ]]; then
+            pushd "$testName" > /dev/null || die
+            chmod +x ./exec
+            if [[ "$verbose" == "true" ]]; then
+                ./exec && testSucceed || testFail
+            else
+                ./exec &> /dev/null && testSucceed || testFail
+            fi
+            popd > /dev/null
+        elif [[ -f "$testName" ]]; then
+            chmod +x ./"$testName"
+            if [[ "$verbose" == "true" ]]; then
+                ./"$testName" && testSucceed || testFail
+            else
+                ./"$testName" &> /dev/null && testSucceed || testFail
+            fi
+        else
+            warn "Could not find the test $testName."
+            testFail
+        fi
+    }
+
+    reportTests() {
+        local succeededWord="tests"
+        if [[ "$succeededTests" == 1 ]]; then
+            succeededWord="test"
+        fi
+        local failedWord="tests"
+        if [[ "$failedTests" == 1 ]]; then
+            failedWord="test"
+        fi
+        local totalWord="tests"
+        if [[ "$totalTests" == 1 ]]; then
+            totalWord="test"
+        fi
+        echo "$succeededTests $succeededWord succeeded and $failedTests $failedWord failed out of a total of $totalTests $totalWord."
+        [[ $(( totalTests - failedTests )) == "$succeededTests" ]] || die "There's a problem in the testing framework."
+    }
 }
+testFramework
 
 trap 'error-notify "An error was reported on ${BASH_SOURCE[0]} line ${LINENO}."' ERR
