Update Git repository using egup-single

diff --git a/scripts/ember-shared-update b/scripts/ember-shared-update
--- a/scripts/ember-shared-update
+++ b/scripts/ember-shared-update
@@ -5,16 +5,29 @@ source ember_bash_setup &> /dev/null || { printf '%b' '\033[1;31m' >&2; echo "A 
 
 trap 'die "A fatal error was reported on ${BASH_SOURCE[0]} line ${LINENO} in $(pwd) at $(emdate)."' ERR
 
-sudo echo
 
-installDir="$(tempDir)"
-cd "$installDir" || die "cd failed"
+if [[ -z "$1" ]]; then
+    sudo echo
+    cp "$0" "$0.tmp"
+    sudo "$0.tmp" --innerExec
+else
+    ((EUID)) && exec sudo -- "$0" "$@" &
 
-git clone https://github.com/ethus3h/ember-shared.git
-(
-    cd ember-shared || die "cd failed"
-    ./configure
-    make
-    sudo make noconf
-    make autodep
-)
+    installDir="$(tempDir)"
+    (
+        cd "$installDir" || die "cd failed"
+
+        git clone https://github.com/ethus3h/ember-shared.git
+        (
+            cd ember-shared || die "cd failed"
+            ./configure
+            make
+            sudo make noconf
+            make autodep
+        )
+    )
+    rm -rf "${installDir:?}"
+
+    wait
+    
+fi
