Update Ember tree

diff --git a/scripts/ember_bash_setup b/scripts/ember_bash_setup
--- a/scripts/ember_bash_setup
+++ b/scripts/ember_bash_setup
@@ -2,10 +2,10 @@
 
 #set -x
 
-export emberSharedVersion='1.1.4.179'
+export emberSharedVersion='1.1.4.180'
 
 # The update script shown here requires there to be only one ebuild of ember-shared in the wreathe-overlay overlay.
-# ( sudo true; newVersion="1.1.4.179"; cd "/Ember Library/Ember satellite projects/ember-shared"; eogup-single; git tag -a "v$newVersion" -m "version"; egup-single .; cd "/Ember Library/Ember satellite projects/wreathe-overlay"; eogup-single; mv app-misc/ember-shared/ember-shared-*.ebuild "app-misc/ember-shared/ember-shared-$newVersion.ebuild"; repoman manifest; egup-single; sudo layman -s wreathe-overlay; sudo emerge ember-shared )
+# ( sudo true; newVersion="1.1.4.180"; cd "/Ember Library/Ember satellite projects/ember-shared"; eogup-single; git tag -a "v$newVersion" -m "version"; egup-single .; cd "/Ember Library/Ember satellite projects/wreathe-overlay"; eogup-single; mv app-misc/ember-shared/ember-shared-*.ebuild "app-misc/ember-shared/ember-shared-$newVersion.ebuild"; repoman manifest; egup-single; sudo layman -s wreathe-overlay; sudo emerge ember-shared )
 
 # To use the --version option of ember_bash_setup, it is necessary to have e8787d06e61943a6874e94985b53bc0a="2dee41bf-53fb-4f65-997f-33bf50bfbb4d" and run ember_bash_setup --version. It may be important to run unset e8787d06e61943a6874e94985b53bc0a afterwards.
 d1875509777f46809ff940e0aad970f0=""
@@ -239,6 +239,7 @@ ia() (
             identifier=""
             remoteNameOverride=""
             remoteNameOverrideFound="false" # Is set to true when waiting for the second half of a two-part --remote-name option
+            outerSucceeded="false"
             for param in "$@"; do
                 if [[ "$remoteNameOverrideFound" == "true" ]]; then
                     # The previous argument was --remote-name, so this one is the remote name to use. Because ia only allows a single file when using --remote-name, this doesn't try to handle the case of multiple --remote-name options.
@@ -319,10 +320,11 @@ ia() (
                 if [[ "$retryCount" -ge 5 ]]; then
                     exit 1
                 fi
+                [[ "$succeeded" == "true" ]] || die "Error uploading in inner function!"
             )
-            retryUntilSuccess 100 30 5 5 uploadRetryInner "$@" && succeeded="true"
-            [[ "$succeeded" == "true" ]] || die "Error uploading!"
-            if [[ "$succeeded" == "true" ]] && [[ "$wantsDelete" == "true" ]]; then
+            retryUntilSuccess 100 30 5 5 uploadRetryInner "$@" && outerSucceeded="true"
+            [[ "$outerSucceeded" == "true" ]] || die "Error uploading!"
+            if [[ "$outerSucceeded" == "true" ]] && [[ "$wantsDelete" == "true" ]]; then
                 for file in "${fileArgs[@]}"; do
                     rm "${file:?}"
                 done
