Update Git repository using egup-single

diff --git a/scripts/ember_bash_setup b/scripts/ember_bash_setup
--- a/scripts/ember_bash_setup
+++ b/scripts/ember_bash_setup
@@ -717,6 +717,21 @@ ia() (
         if [[ -e "$path" ]] && [[ "$(wc -c < "$path")" -gt 3 ]]; then
             cat "$path"
         else
+            temp="$(tempFile)"
+            retryUntilSuccess 30 30 5 5 wget -qO - "https://archive.org/download/$ident/$ident"_meta.xml > "$temp"
+            if [[ 0 != "$?" ]]; then
+                die "Could not get meta XML for $ident: error first download."
+            fi
+            tempSha="$(sha512sum "$temp" | awk '{print $1;}')"
+            [[ -n "$tempSha" ]] || die "Checksum empty while getting meta XML for $ident"
+            rm "$temp"
+            [[ -e "$temp" ]] && die "Temporary file unexpectedly exists while getting meta XML for $ident"
+            retryUntilSuccess 30 30 5 5 wget -qO - "https://archive.org/download/$ident/$ident"_meta.xml > "$temp"
+            if [[ 0 != "$?" ]]; then
+                die "Could not get meta XML for $ident: error second download."
+            fi
+            [[ "$(sha512sum "$temp" | awk '{print $1;}')" == "$tempSha" ]] || die "meta XML for $ident was different when downloaded twice"
+            mv "$temp" "$path"
             retryUntilSuccess 30 30 5 5 command ia metadata "$ident" > "$path"
             if [[ 0 != "$?" ]]; then
                 die "Could not get metadata for $ident."
