Update Git repository using egup-single

diff --git a/scripts/ember_bash_setup b/scripts/ember_bash_setup
--- a/scripts/ember_bash_setup
+++ b/scripts/ember_bash_setup
@@ -384,7 +384,7 @@ ia() (
                         else
                             fileToQuery="$remoteNameOverride"
                         fi
-                        retryUntilSuccess 5000 60 5 5 iasha1 "$identifier/$fileToQuery" > /dev/null || die "Could not get checksum for uploaded file $identifier/$fileToQuery."
+                        retryUntilSuccess 100 120 5 5 iasha1 "$identifier/$fileToQuery" > /dev/null || die "Could not get checksum for uploaded file $identifier/$fileToQuery."
                         checksumLine="$(iasha1 "$identifier/$fileToQuery")"
                         if [[ "$checksumLine" != "$knownChecksum" ]]; then
                             die "ERROR! Checksum known by Internet Archive $checksumLine does not match saved checksum known locally $knownChecksum."
@@ -400,7 +400,7 @@ ia() (
                 fi
                 [[ "$succeeded" == "true" ]] || die "Error uploading in inner function!"
             )
-            retryUntilSuccess 100 30 5 5 uploadRetryInner "$@" && outerSucceeded="true"
+            retryUntilSuccess 10 120 5 5 uploadRetryInner "$@" && outerSucceeded="true"
             [[ "$outerSucceeded" == "true" ]] || die "Error uploading!"
             if [[ "$outerSucceeded" == "true" ]] && [[ "$wantsDelete" == "true" ]]; then
                 for file in "${fileArgs[@]}"; do
