Update Git repository using egup-single

diff --git a/scripts/ember_bash_setup b/scripts/ember_bash_setup
--- a/scripts/ember_bash_setup
+++ b/scripts/ember_bash_setup
@@ -614,12 +614,12 @@ ia() (
                 if [[ 0 != "$?" ]]; then
                     die "Could not get list for $ident: error fetching."
                 else
-                if [[ -e "$path" ]] && [[ "$(wc -c < "$path")" -gt 1 ]]; then
-                    cat "$path"
-                else
-                    rm "$path" || die "Could not remove path to failed retrieval of list for $ident"
-                    die "Could not get list for $ident"
-                fi
+                    if [[ -e "$path" ]] && [[ "$(wc -c < "$path")" -gt 1 ]]; then
+                        cat "$path"
+                    else
+                        rm "$path" || die "Could not remove path to failed retrieval of list for $ident"
+                        die "Could not get list for $ident"
+                    fi
                 fi
             fi
         fi
