Update Ember tree

diff --git a/scripts/ember_bash_setup b/scripts/ember_bash_setup
--- a/scripts/ember_bash_setup
+++ b/scripts/ember_bash_setup
@@ -620,12 +620,26 @@ tempFile() {
     echo "$fileId"
 }
 
+crystallize-getconf() (
+    local save_traps
+    save_traps="$(trap)"
+    trap 'error-notify "An error was reported in the sponge wrapper with the arguments $* on ${BASH_SOURCE[0]} line ${LINENO} in $(pwd) at $(emdate)."' ERR
+    trap - EXIT
+    [[ -n "$CrystalWorkdirOverride54ae685dc782437c99bc46c7a1211377" ]] && echo 
+    local oldTmpdir="$TMPDIR"
+    TMPDIR="$(crystallize-getconf WorkDirectory)" || TMPDIR="$oldTmpdir"
+    export TMPDIR
+    command sponge "$@"
+    eval "$save_traps"
+)
+
 sponge() (
     local save_traps
     save_traps="$(trap)"
     trap 'error-notify "An error was reported in the sponge wrapper with the arguments $* on ${BASH_SOURCE[0]} line ${LINENO} in $(pwd) at $(emdate)."' ERR
     trap - EXIT
-    TMPDIR="$(crystallize-getconf WorkDirectory)"
+    local oldTmpdir="$TMPDIR"
+    TMPDIR="$(crystallize-getconf WorkDirectory)" || TMPDIR="$oldTmpdir"
     export TMPDIR
     command sponge "$@"
     eval "$save_traps"
