Update Git repository using egup-single

diff --git a/scripts/ember_bash_setup b/scripts/ember_bash_setup
--- a/scripts/ember_bash_setup
+++ b/scripts/ember_bash_setup
@@ -2,10 +2,10 @@
 
 #set -x
 
-export emberSharedVersion='1.1.4.308'
+export emberSharedVersion='1.1.4.309'
 
 # The update script shown here requires there to be only one ebuild of ember-shared in the wreathe-overlay overlay.
-# ( sudo true; newVersion="1.1.4.308"; cd "/Ember Library/Ember satellite projects/ember-shared"; eogup-single; git tag -a "v$newVersion" -m "version"; egup-single .; cd "/Ember Library/Ember satellite projects/wreathe-overlay"; eogup-single; mv app-misc/ember-shared/ember-shared-*.ebuild "app-misc/ember-shared/ember-shared-$newVersion.ebuild"; repoman manifest; egup-single; sudo emerge --sync wreathe-overlay; sudo emerge ember-shared; sudo dispatch-conf )
+# ( sudo true; newVersion="1.1.4.309"; cd "/Ember Library/Ember satellite projects/ember-shared"; eogup-single; git tag -a "v$newVersion" -m "version"; egup-single .; cd "/Ember Library/Ember satellite projects/wreathe-overlay"; eogup-single; mv app-misc/ember-shared/ember-shared-*.ebuild "app-misc/ember-shared/ember-shared-$newVersion.ebuild"; repoman manifest; egup-single; sudo emerge --sync wreathe-overlay; sudo emerge ember-shared; sudo dispatch-conf )
 
 # To use the --version option of ember_bash_setup, it is necessary to have e8787d06e61943a6874e94985b53bc0a="2dee41bf-53fb-4f65-997f-33bf50bfbb4d" and run ember_bash_setup --version. It may be important to run unset e8787d06e61943a6874e94985b53bc0a afterwards.
 d1875509777f46809ff940e0aad970f0=""
@@ -127,7 +127,7 @@ setVariableToCommandOutput() {
     save_traps="$(trap)"
     trap - ERR
     IFS= read -rd '' "$emSetVariableToCommandOutputVar" < <( "$@" )
-    trap 'die "A fatal error was reported on ${BASH_SOURCE[0]} line ${LINENO} in $(pwd) at $(emdate)."' ERR
+    trap 'die "A fatal error (#$?) was reported on ${BASH_SOURCE[0]} line ${LINENO} in $(pwd) at $(emdate)."' ERR
     eval "$save_traps"
 }
 
@@ -161,7 +161,7 @@ defaultEditor() {
 
 emdate() (
     # If changing this, also change the copy in the error-notify script and possibly also the copy in the emberMacGNUUpgrade script.
-    trap 'die "A fatal error was reported on ${BASH_SOURCE[0]} line ${LINENO} in $(pwd)."' ERR
+    trap 'die "A fatal error (#$?) was reported on ${BASH_SOURCE[0]} line ${LINENO} in $(pwd)."' ERR
 
     local temp
     temp="$(date +%Y-%m-%d-%H-%M-%S-%N)_$(xxd -pu <<< "$(date +%z)")"
@@ -169,7 +169,7 @@ emdate() (
 )
 
 date-uuid() (
-    trap 'die "A fatal error was reported on ${BASH_SOURCE[0]} line ${LINENO} in $(pwd) at $(emdate)."' ERR
+    trap 'die "A fatal error (#$?) was reported on ${BASH_SOURCE[0]} line ${LINENO} in $(pwd) at $(emdate)."' ERR
 
     local temp
     temp="$(emdate)-$(python -c 'import uuid; print str(uuid.uuid4())')"
diff --git a/scripts/error-notify b/scripts/error-notify
--- a/scripts/error-notify
+++ b/scripts/error-notify
@@ -1,7 +1,7 @@
 #!/usr/bin/env bash
 emdate() (
     # If changing this, also change the copy in the ember_bash_setup script.
-    trap 'die "A fatal error was reported on ${BASH_SOURCE[0]} line ${LINENO} in $(pwd)."' ERR
+    trap 'die "A fatal error (#$?) was reported on ${BASH_SOURCE[0]} line ${LINENO} in $(pwd)."' ERR
 
     temp="$(date +%Y-%m-%d-%H-%M-%S-%N)_$(xxd -pu <<< "$(date +%z)")"
     echo "${temp//-/}"
@@ -25,7 +25,7 @@ else
 fi
 printf '%b' '\033[1;31m' >&2
 printf '%s\n' "$(ps -o args= $PPID)" >&2
-printf '%s\n' 'failed with the error on '"${BASH_SOURCE[0]} line ${LINENO} in $(pwd) at $(emdate)"':' >&2
+printf '%s\n' 'failed with the error (#$?) on '"${BASH_SOURCE[0]} line ${LINENO} in $(pwd) at $(emdate)"':' >&2
 printf '%s' "${@+$@$'\n'}" >&2
 printf '%b' '\033[0m' >&2
 
