Update Git repository using egup-single

diff --git a/scripts/ember_bash_setup b/scripts/ember_bash_setup
--- a/scripts/ember_bash_setup
+++ b/scripts/ember_bash_setup
@@ -773,13 +773,12 @@ git-bulk-sync() {
 
 get-default-firefox-profile() {
     # from https://askubuntu.com/questions/239543/get-the-default-firefox-profile-directory-from-bash
-    cd ~/.mozilla/firefox/
-    if [[ $(grep '\[Profile[^0]\]' profiles.ini) ]]; then
-        PROFPATH=$(grep -E '^\[Profile|^Path|^Default' profiles.ini | grep -1 '^Default=1' | grep '^Path' | cut -c6-)
+    cd ~/.mozilla/firefox || die "Could not cd to ~/.mozilla/firefox"
+    if grep -q '\[Profile[^0]\]' profiles.ini; then
+        grep -E '^\[Profile|^Path|^Default' profiles.ini | grep -1 '^Default=1' | grep '^Path' | cut -c6-
     else
-        PROFPATH=$(grep 'Path=' profiles.ini | sed 's/^Path=//')
+        grep 'Path=' profiles.ini | sed 's/^Path=//'
     fi
-    echo "$PROFPATH"
 }
 
 bigSponge() (
