Update Git repository using egup-single

diff --git a/scripts/ember_bash_setup b/scripts/ember_bash_setup
--- a/scripts/ember_bash_setup
+++ b/scripts/ember_bash_setup
@@ -613,17 +613,17 @@ ia() (
                 temp="$(tempFile)"
                 retryUntilSuccess 30 30 5 5 command ia list "$ident" > "$temp"
                 if [[ 0 != "$?" ]]; then
-                    die "Could not get files XML for $ident: error first download."
+                    die "Could not get list for $ident: error first download."
                 fi
                 tempSha="$(sha512sum "$temp" | awk '{print $1;}')"
-                [[ -n "$tempSha" ]] || die "Checksum empty while getting files XML for $ident"
+                [[ -n "$tempSha" ]] || die "Checksum empty while getting list for $ident"
                 rm "$temp"
                 [[ -e "$temp" ]] && die "Temporary file unexpectedly exists while getting files XML for $ident"
                 retryUntilSuccess 30 30 5 5 command ia list "$ident" > "$temp"
                 if [[ 0 != "$?" ]]; then
-                    die "Could not get files XML for $ident: error second download."
+                    die "Could not get list for $ident: error second download."
                 fi
-                [[ "$(sha512sum "$temp" | awk '{print $1;}')" == "$tempSha" ]] || die "files XML for $ident was different when downloaded twice"
+                [[ "$(sha512sum "$temp" | awk '{print $1;}')" == "$tempSha" ]] || die "list for $ident was different when downloaded twice"
                 mv "$temp" "$path"
                 if [[ 0 != "$?" ]]; then
                     die "Could not get list for $ident: error moving."
