Update Git repository using egup-single

diff --git a/scripts/ember_bash_setup_core b/scripts/ember_bash_setup_core
--- a/scripts/ember_bash_setup_core
+++ b/scripts/ember_bash_setup_core
@@ -23,6 +23,15 @@ die() {
     exit 1
 }
 
+emdate() (
+    # If changing this, also change the copy in the error-notify script and possibly also the copy in the emberMacGNUUpgrade script.
+    trap 'die "A fatal error was reported on ${BASH_SOURCE[0]} line ${LINENO} in $(pwd)."' ERR
+
+    local temp
+    temp="$(date -u +%Y-%m-%d-%H-%M-%S-%N)U$(xxd -pu <<< "$(date +%z)")"
+    echo "${temp//-/}"
+)
+
 setVariableToCommandOutput() {
     if [[ "$1" == "emSetVariableToCommandOutputVar" ]]; then
         return 1
