Update Ember tree

diff --git a/scripts/error-notify b/scripts/error-notify
--- a/scripts/error-notify
+++ b/scripts/error-notify
@@ -1,4 +1,11 @@
 #!/usr/bin/env bash
+emdate() (
+    # If changing this, also change the copy in the ember_bash_setup script.
+    trap 'die "A fatal error was reported on ${BASH_SOURCE[0]} line ${LINENO}."' ERR
+
+    temp="$(date +%Y-%m-%d-%H-%M-%S-%N)_$(xxd -pu <<< "$(date +%z)")"
+    echo "${temp//-/}"
+)
 # If first argument is an integer, print the remaining arguments and exit with the first argument as the exit status. Otherwise, print all the arguments and exit with exit status 1. If there are no arguments to print, don't print anything.
 if [[ $# -eq 0 ]]; then
     # There are no arguments; just exit
