Update Git repository using egup-single

diff --git a/data/app-buildsystem/support/autodep b/data/app-buildsystem/support/autodep
--- a/data/app-buildsystem/support/autodep
+++ b/data/app-buildsystem/support/autodep
@@ -1,6 +1,6 @@
 #!/usr/bin/env bash
 
-if ! ebs_loc="$(type -P "ember_bash_setup")" || [[ -z $ebs_loc ]]; then
+if ! ebs_loc="$(type -P "ember_bash_setup_core")" || [[ -z $ebs_loc ]]; then
     # Try automatically building ember-shared
     mkdir .buildsystem-temp
     (
@@ -15,7 +15,7 @@ if ! ebs_loc="$(type -P "ember_bash_setup")" || [[ -z $ebs_loc ]]; then
 fi
 
 # shellcheck disable=SC1091
-source ember_bash_setup &> /dev/null || { printf '%b' '\033[1;31m' >&2; echo "A fatal error was reported on ${BASH_SOURCE[0]} line ${LINENO} in $(pwd): The required dependency ember-shared could not be found (or ember_bash_setup could not be sourced for some other reason)." >&2; printf '%b' '\033[0m' >&2; exit 1; }
+source ember_bash_setup_core &> /dev/null || { printf '%b' '\033[1;31m' >&2; echo "A fatal error was reported on ${BASH_SOURCE[0]} line ${LINENO} in $(pwd): The required dependency ember-shared could not be found (or ember_bash_setup_core could not be sourced for some other reason)." >&2; printf '%b' '\033[0m' >&2; exit 1; }
 #set -x
 
 trap 'die "A fatal error was reported on ${BASH_SOURCE[0]} line ${LINENO} in $(pwd)."' ERR
